enum CollectionActionTypes {
  GET_COLLECTIONS = "GET_COLLECTIONS",
  ADD_COLLECTIONS = "ADD_COLLECTIONS",
  PUT_COLLECTIONS = "PUT_COLLECTIONS",
  PUSH_COLLECTIONS = "PUSH_COLLECTIONS",
  PUT_PENDING_COLLECTIONS = "PUT_PENDING_COLLECTIONS",
  PUT_ERROR_COLLECTIONS = "PUT_ERROR_COLLECTIONS",
  PUT_COLLECTION_QUERY = "PUT_COLLECTION_QUERY",
}
export default CollectionActionTypes;
