enum UserActionTypes {
  GET_USERS = "GET_USERS",
  ADD_USERS = "ADD_USERS",
  PUT_USERS = "PUT_USERS",
  PUSH_USERS = "PUSH_USERS",
  PUT_PENDING_USERS = "PUT_PENDING_USERS",
  PUT_ERROR_USERS = "PUT_ERROR_USERS",
  PUT_USER_QUERY = "PUT_USER_QUERY",
}
export default UserActionTypes;
