enum PhotoActionTypes {
  GET_PHOTOS = "GET_PHOTOS",
  ADD_PHOTOS = "ADD_PHOTOS",
  PUT_PHOTOS = "PUT_PHOTOS",
  PUSH_PHOTOS = "PUSH_PHOTOS",
  PUT_PENDING_PHOTOS = "PUT_PENDING_PHOTOS",
  PUT_ERROR_PHOTOS = "PUT_ERROR_PHOTOS",
  PUT_PHOTO_QUERY = "PUT_PHOTO_QUERY",
}
export default PhotoActionTypes;
