enum PhotoActionsTypes {
  GET_PHOTOS = "GET_PHOTOS",
  PUT_PHOTOS = "PUT_PHOTOS",
  PUT_PENDING_PHOTOS = "PUT_PENDING_PHOTOS",
  PUT_ERROR_PHOTOS = "PUT_ERROR_PHOTOS",
  PUT_LOAD_MORE = "PUT_LOAD_MORE",
  PUT_PHOTO_QUERY = "PUT_PHOTO_QUERY"
}

export default PhotoActionsTypes;
